# Generated by Django 4.0.6 on 2024-02-04 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='socials',
        ),
    ]
